server:
  port: 8080
  servlet:
    context-path: /st-visualization
spring:
  application:
    name: st-visualization
  datasource:
    url: jdbc:postgresql://localhost:5432/st_visualization
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always #服务启动时执行schema.sql
  main:
    allow-circular-references: true
  task:
    execution:
      thread-name-prefix: async-
      pool:
        core-size: 8
        queue-capacity: 100
        max-size: 15
        keep-alive: 60s
        allow-core-thread-timeout: true


